### ISSUE TITLE
Does not seem to work in this case...

### ISSUE THREAD

**Issue by some-dingdong** [WCharacter/RDTSC-KVM-Handler#1]
Im using a Proxmox VE on AMD. It uses a custom kernel. However, I have managed to create a patch, apply it, and compile into a deb package. Then when installed and system restarted I cant see it working. Pafish tests still fails at RDTSC VM EXIT and I cant find this in my syslog: 
`[handle_rdtsc] fake rdtsc svm function is working` 
After many compiling and installing I have managed to verify that my patches are actually used. Except this, every thing works, but not yours little code. I am sure because it have compiled and VM booting (failing too boot with different patches from reddit and getting syslogs). I have tried with both rdtscp on and off but still not working.
I have hope that you are still active on this repo and would like to get any information to fix this problem in my case

**Comment by WCharacter** [comment]
I'm not sure why this is happening. To check the logs i use dmesg command. If a patch is really applied this message should be in your kernel logs. My patch divides the timings, so if you see on your virtual machine in task manager that your cpu frequency is 0.1 or some other low value it's working.
