### ISSUE TITLE
Fedora

### ISSUE THREAD

**Issue by aamaanaa** [WCharacter/RDTSC-KVM-Handler#19]
![Screenshot from 2024-03-06 15-10-19](https://github.com/WCharacter/RDTSC-KVM-Handler/assets/55531822/0c75b98d-940f-4c38-9a94-cf55a5ee4e41)

using the tool in the image i can see red hat is there

i use spice server and video QXL

**Comment by Samuil1337** [comment]
Sir, I am sorry but this patch doesn't spoof the names of virtual devices, but the RDTSC time stamps reported by KVM. The patch you are looking for is this: https://github.com/zhaodice/qemu-anti-detection

**Comment by aamaanaa** [comment]
yes i used that but vm exit is not spoofed wich requires to recompile the fedora kernel
