### ISSUE TITLE
Hypervisor disable causing stuttering

### ISSUE THREAD

**Issue by xiopt** [WCharacter/RDTSC-KVM-Handler#3]
I patched the kernel like in the guide, everything works well, the message is in the kernel logs but when I try running a game (Apex Legends in my case) every time I move the mouse the game stutters like hell.
Until I patched the kernel I had the hypervisor feature required in CPU options and everything was working fine but after disabling the stuttering is back.
I think the problem is caused by mouse move and the game are competing for the same CPU time.
OS: Ubuntu 20.04
Kernel: 5.5
u64 fake_diff = diff / 16;
CPU: Intel i7-8700k
Here is my win10 guest config: https://pastebin.com/7d0sBjMx

**EDIT**: It looks like if I lower the mouse polling rate the stuttering is much less present.

**Comment by xiopt** [comment]
Looks like it's a problem specific for VirtIO Mouse so I am going to close the issue since it's not related to this patch.

**Comment by WCharacter** [comment]
I have the same problem on my I7 8700. The problem fixed itself after i reinstalled windows on my virtual machine. I don't know the reason of this stutters, so i can't provide any information about it.
