### ISSUE TITLE
how would you calculate the divided number?

### ISSUE THREAD

**Issue by mint-xoxo** [WCharacter/RDTSC-KVM-Handler#4]
how would you calculate the divided number? im confused i have 3.6ghz in my vm so would i just leave it at default or need to change it

**Comment by mint-xoxo** [comment]
also it does not seem to load

**Comment by WCharacter** [comment]
I tried some numbers and come to conclusion that 0.2 Ghz (if you divide 3.6 by 18 you will get this number) is stable and works 90% of the time in al-khazer.
