### ISSUE TITLE
MacOS issues - extremely slow

### ISSUE THREAD

**Issue by llitz** [WCharacter/RDTSC-KVM-Handler#5]
Someone reported on reddit this issue:

https://www.reddit.com/r/VFIO/comments/lckplp/psa_do_not_use_the_rtdsc_bypass_kernel_patch_if

Apparently MacOS suffers from the patch. I don't have a way to test it, but thought it would be good to report here, perhaps someone can help testing.

**Comment by WCharacter** [comment]
Thanks for posting, i don't have macOS too. This patch was never intended to be used for macOS virtualization.

**Comment by llitz** [comment]
Agreed.

It might be possible to reproduce the behavior under FreeBSD.
From a side of curiosity, perhaps this could point to some operation that slow down all systems, except the performance impact on MacOS is "easily" measured.

Worst case is this leads to something that can't be fixed.
Best case is this leads to something that can generate some small boost in performance for Windows or better emulate a real hardware, possibly blocking another way to detect the VM.

**Comment by WCharacter** [comment]
This patch makes windows to think that you have cpu with 0.2-0.4 Ghz of clock speed, because you basically divide your difference between two rdtsc calls by 16 or your own number. I think this is the main reason why macOS or FreeBSD may be slower if they depend on this call.
